"""
Phase 6.2 — Executor interface.

The LivePaperRuntime talks ONLY to this interface. It does not know or care
whether the concrete implementation is:
  - PaperExecutor  (simulated fills, no real orders — Phase 6)
  - BrokerExecutor (real Kite orders — future phase)

Contract:
  submit_order(req)          → order_id string
  cancel_order(order_id)     → bool success
  modify_order(order_id, ..) → bool success
  get_order_status(id)       → OrderStatus
  get_positions()            → Dict[instrument → net_qty]
  get_fills()                → List[OrderStatus] since last poll

Design principles:
  - All methods are synchronous and non-blocking (no async)
  - Fills are always surfaced via get_fills() polling, not callbacks
  - The interface is intentionally minimal — complexity lives in implementations
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional


@dataclass
class OrderRequest:
    """Everything needed to place an order."""
    order_id: str                # generated by caller (uuid); idempotency key
    instrument: str
    direction: str               # BUY | SELL
    order_type: str              # MARKET | LIMIT
    quantity: int                # in lots × lot_size (units, not lots)
    price: Optional[float]       # required for LIMIT orders
    strategy_name: str
    signal_timestamp: datetime
    metadata: Dict = field(default_factory=dict)


@dataclass
class OrderStatus:
    """Current state of one order."""
    order_id: str
    instrument: str
    direction: str
    quantity: int
    status: str                  # PENDING | FILLED | PARTIAL | CANCELLED | REJECTED
    filled_qty: int = 0
    fill_price: Optional[float] = None
    fill_time: Optional[datetime] = None
    message: str = ''
    metadata: Dict = field(default_factory=dict)

    @property
    def is_done(self) -> bool:
        return self.status in ('FILLED', 'CANCELLED', 'REJECTED')

    @property
    def is_filled(self) -> bool:
        return self.status == 'FILLED' and self.filled_qty > 0


class Executor(ABC):
    """
    Interface for order execution. The runtime only speaks this protocol.
    Paper and real implementations satisfy the same contract.
    """

    @abstractmethod
    def submit_order(self, req: OrderRequest) -> str:
        """
        Submit an order. Returns the order_id (same as req.order_id).
        Raises ValueError if the request is invalid.
        """
        raise NotImplementedError

    @abstractmethod
    def cancel_order(self, order_id: str) -> bool:
        """Cancel a pending order. Returns True if cancelled, False if already done."""
        raise NotImplementedError

    @abstractmethod
    def modify_order(self, order_id: str, new_price: Optional[float] = None,
                     new_qty: Optional[int] = None) -> bool:
        """Modify a pending LIMIT order. Returns True if modified."""
        raise NotImplementedError

    @abstractmethod
    def get_order_status(self, order_id: str) -> Optional[OrderStatus]:
        """Return current status of one order, or None if unknown."""
        raise NotImplementedError

    @abstractmethod
    def get_positions(self) -> Dict[str, int]:
        """Return net position in units for each instrument {instrument: net_qty}."""
        raise NotImplementedError

    @abstractmethod
    def get_fills(self) -> List[OrderStatus]:
        """
        Return all newly-filled orders since the last call.
        Implementations must return each fill exactly once.
        """
        raise NotImplementedError

    @abstractmethod
    def get_open_orders(self) -> List[OrderStatus]:
        """Return all currently pending orders."""
        raise NotImplementedError

    def reset_session(self) -> None:
        """Reset intraday state at session start (09:15). Override if needed."""
