"""
CLI: generate a synthetic option-chain archive aligned to a NIFTY/BANKNIFTY OHLCV CSV.

Usage:
    python3 tools/export_synthetic_chain.py \\
        --ohlcv data/raw/NIFTY.csv \\
        --underlying NIFTY \\
        --out data/option_chain_snapshots \\
        --atm-iv 0.15 \\
        --daily-iv-variation \\
        --sample-every 1

Why this exists:
    Phase 4.8 needs the HistoricalOptionChainFeed code path tested end-to-end
    before real broker data arrives. This CLI produces an archive in the exact
    Parquet schema the real loader expects, but the underlying prices are
    synthetic Black-Scholes — so data_source_warning stays on automatically
    via the 'synthetic' data_origin in the manifest.
"""
import argparse
import sys
from datetime import datetime
from pathlib import Path

# Make `src` importable when running as `python3 tools/...` from project root
_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent))

from src.feeds.chain_archive import export_from_ohlcv  # noqa: E402
from src.feeds.chain_archive_schema import ArchiveManifest, SCHEMA_VERSION, ORIGIN_SYNTHETIC  # noqa: E402
from src.feeds.option_chain_snapshot import SyntheticOptionChainFeed, WeeklyExpiryProvider  # noqa: E402


def main(argv=None):
    parser = argparse.ArgumentParser(description='Export synthetic chain archive aligned to OHLCV')
    parser.add_argument('--ohlcv', required=True, help='Path to NIFTY/BANKNIFTY OHLCV CSV')
    parser.add_argument('--underlying', required=True, help='Underlying symbol e.g. NIFTY')
    parser.add_argument('--out', required=True, help='Archive root output directory')
    parser.add_argument('--atm-iv', type=float, default=0.15)
    parser.add_argument('--skew', type=float, default=-0.02)
    parser.add_argument('--smile', type=float, default=0.30)
    parser.add_argument('--expiry-weekday', type=int, default=3, help='0=Mon..6=Sun; default 3 (Thu)')
    parser.add_argument('--strike-interval', type=float, default=50.0)
    parser.add_argument('--num-strikes', type=int, default=20, help='Strikes each side of ATM')
    parser.add_argument('--daily-iv-variation', action='store_true',
                        help='Use sinusoidal day-over-day ATM IV variation')
    parser.add_argument('--sample-every', type=int, default=1,
                        help='Down-sample input bars by this factor (1 = every bar)')
    args = parser.parse_args(argv)

    feed = SyntheticOptionChainFeed(
        atm_iv=args.atm_iv,
        skew=args.skew,
        smile=args.smile,
        strike_interval={args.underlying: args.strike_interval},
        num_strikes_each_side=args.num_strikes,
        expiry_provider=WeeklyExpiryProvider(weekday=args.expiry_weekday),
        daily_iv_variation=args.daily_iv_variation,
    )

    manifest = ArchiveManifest(
        schema_version=SCHEMA_VERSION,
        data_origin=ORIGIN_SYNTHETIC,
        generated_at=datetime.now(),
        notes=(f"Generated by tools/export_synthetic_chain.py from {args.ohlcv}; "
                f"atm_iv={args.atm_iv}, skew={args.skew}, smile={args.smile}, "
                f"daily_iv_variation={args.daily_iv_variation}. "
                f"Not valid for edge claims — see Iron_Fly_Strategy_Spec_v2.md §13."),
    )

    print(f">> Exporting synthetic chain archive")
    print(f"   OHLCV input : {args.ohlcv}")
    print(f"   Underlying  : {args.underlying}")
    print(f"   Output root : {args.out}")
    print(f"   Sampling    : every {args.sample_every} bar(s)")
    out = export_from_ohlcv(
        feed=feed,
        ohlcv_csv=Path(args.ohlcv),
        out_dir=Path(args.out),
        underlying=args.underlying,
        manifest=manifest,
        sample_every_n_minutes=args.sample_every,
    )
    print(f">> Done. Archive root: {out}")
    print(f"   Manifest written with data_origin='{ORIGIN_SYNTHETIC}' — "
            f"data_source_warning will remain on when this archive is loaded.")
    return 0


if __name__ == '__main__':
    sys.exit(main())
